---
- hosts: servers
  become: yes
  tasks:
    - name: update cache
      pacman:
        update_cache: yes
      tags: update

    - name: Install nginx
      pacman:
        name: "{{ nginx_service }}"
        state: present
      tags: nginx

    - name: enable and start nginx
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: yes
      tags: nginx

    - name: Install VPN server (openvpn)
      pacman:
        name: "{{ vpn_package }}"
        state: present
      tags: vpn

    - name: restart nginx
      service:
        name: "{{ nginx_service }}"
        state: restarted
      tags: returmas
